import fs from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const compiled=ts.transpileModule(fs.readFileSync('src/lib/siteAnalytics.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {startSiteAnalytics}=await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
let now=0,focused=true,interval,retry=true;const requests=[],beacons=[],store=new Map();
const doc=new EventTarget();Object.assign(doc,{visibilityState:'visible',hasFocus:()=>focused,referrer:'',querySelector:()=>({getBoundingClientRect:()=>({height:1000,top:0})})});
const win=new EventTarget();Object.assign(win,{setInterval:fn=>{interval=fn;return 1;},clearInterval:()=>{}});
Object.assign(globalThis,{document:doc,window:win,innerHeight:500,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}});
Object.defineProperty(globalThis,'navigator',{value:{language:'es',sendBeacon:(_url,body)=>{beacons.push(body);return true;}},configurable:true});
Object.defineProperty(globalThis,'performance',{value:{now:()=>now},configurable:true});
globalThis.fetch=async (_url,options)=>{const body=JSON.parse(options.body);requests.push(body);if(retry){retry=false;throw Error('simulated timeout');}return {ok:true,json:async()=>({tracked:true})};};
const settle=()=>new Promise(resolve=>setImmediate(resolve));
const stop=startSiteAnalytics('/home');await settle();
now=30000;interval();await settle();
assert.equal(requests[0].visitId,requests[1].visitId,'retry retains identity');
now=31000;focused=false;win.dispatchEvent(new Event('blur'));
now=91000;focused=true;win.dispatchEvent(new Event('focus'));
now=92000;stop();await settle();
let samples=await Promise.all(beacons.map(async b=>JSON.parse(await b.text())));
assert.equal(samples.at(-1).activeMs,32000,'hidden minute excluded');
assert.equal(samples.at(-1).scroll,50);
now=200000;assert.equal(samples.at(-1).activeMs,32000,'cleanup stops clock');
const stop2=startSiteAnalytics('/wiki');await settle();
assert.equal(requests.at(-1).previousPath,'/home');
now=201000;win.dispatchEvent(new Event('pagehide'));
now=260000;win.dispatchEvent(new Event('pageshow'));
now=261000;stop2();await settle();
samples=await Promise.all(beacons.map(async b=>JSON.parse(await b.text())));
assert.equal(samples.at(-1).activeMs,2000,'BFCache time excluded');
console.log('PASS: retry identity, focused time, cleanup, page transitions, BFCache suspension and scroll.');
