name = "infraphysics-counters"
main = "src/index.ts"
compatibility_date = "2026-09-01"
workers_dev = false
preview_urls = false

[[durable_objects.bindings]]
name = "COUNTERS"
class_name = "Counters"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Counters"]
